name: "Update"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  updater:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install
      run:  curl -s https://raw.githubusercontent.com/blackbirdstudiorus/LoganetXIPTV/main/LoganetXAll.m3u > playlist.m3u
    - name: Install 2
      run: curl -s https://raw.githubusercontent.com/iptv-org/iptv/master/streams/ru.m3u | grep -A 1 'PervyyTulskiy' | sed 's/tvg-id="PervyyTulskiy.ru"/group-title="Общие"/' >> playlist.m3u
    - name: install 3
      run: echo -e "#EXTINF:-1 tvg-logo=\"https://picon.pp.ua/setanta-sports.png\" group-title=\"Спорт\", Setanta Sports 1\nhttps://bkm.beetv.kz/btv/live/hls/000004498.m3u8\n#EXTINF:-1 tvg-logo=\"https://picon.pp.ua/setanta-sports-plus.png\" group-title=\"Спорт\", Setanta Sports 2\nhttps://bkm.beetv.kz/btv/live/hls/000004499.m3u8" >> playlist.m3u
    - name: install 4
      run: |
          DATA=$(curl -s https://raw.githubusercontent.com/MaximKiselev/iptv/main/playlist.m3u)
          CURRENT_CHANNEL=$(echo "$DATA" | grep -B 2 'expires')
          EXPIRATION=$(echo "$DATA" | grep -oP '(?<=expires/).*?(?=/)')
          CURRENT_TIMESTAMP=$(date +%s%3N)
      
          if [ "$CURRENT_TIMESTAMP" -gt "$EXPIRATION" ]; then
            STREAM_URL=$(curl -s --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" https://ok.ru/videoembed/977507065564 | grep -oP '(?<=hlsMasterPlaylistUrl\\&quot;:\\&quot;)https://.*?video\.m3u8')
             if [ "$(echo "$STREAM_URL" | wc -c)" -gt 20 ]; then
               echo "$STREAM_URL" | sed 's/^/#EXTINF:-1 group-title="Общие",Первый Тульский\n#EXTVLCOPT:http-user-agent=Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/121.0.0.0 Safari\/537.36\n/' >> playlist.m3u
             else
               echo "$CURRENT_CHANNEL" >> playlist.m3u
             fi
          else 
             echo "$CURRENT_CHANNEL" >> playlist.m3u
          fi   
    - name: Commit files
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        set -euo pipefail

        git remote add github "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git pull github ${GITHUB_REF} --ff-only

        # Get name & email from 1st commit (needs `fetch-depth: 0` in step `actions/checkout@v3`)
        git config --local user.email "$(git log --format='%ae' --reverse | head -1)"
        git config --local user.name "$(git log --format='%an' --reverse | head -1)"

        # try commit
        git add .
        if [ -z "$(git status --porcelain)" ]; then
          echo 'No changes'
          exit 0
        fi
        git commit -m "Auto-update"

        # push changes
        git push github HEAD:${GITHUB_REF}
